courses = ['History', 'Math', 'Physics', 'CompSci']
# print(courses)
# print(courses[0])
# print(courses[1])
# print(courses[2])
# print(courses[3])
# print(courses[4])
# print('*******')
# print(courses[-1])
# print('*******')
# courses.reverse()
# print(courses)
# print('*******')
# courses.insert(0, 'Art')
# print(courses)
# print('*******')
# popped = courses.remove('')
# print(popped)
# print(courses)
# print('Original List = {} '.format(courses))
# courses.sort()
# print('Called sort() method')
# print('Sort() Method = {} '.format(courses))
# print('*******')
# courses = ['History', 'Math', 'Physics', 'CompSci']
# print('Original List, Before= {} '.format(courses))
# sorted_courses = sorted(courses)
# print('Called sorted() function')
# print('Original List, After = {} '.format(courses))
# print('Sorted() Function on original list = {} '.format(courses))
# print('Sorted() Function on new sorted_courses list = {} '.format(sorted_courses))
# print('*******')
